"""Application entrypoints."""

from .service_factory import (
    create_declarations_client,
    create_declarations_service,
    create_default_declarations_client,
    create_default_declarations_service,
    create_diagnostics_client,
    create_diagnostics_service,
    create_default_diagnostics_client,
    create_default_diagnostics_service,
    create_default_lsp_core_client,
    create_default_lsp_core_service,
    create_default_lsp_assist_client,
    create_default_lsp_assist_service,
    create_default_search_core_client,
    create_default_search_core_service,
    create_default_mathlib_nav_client,
    create_default_mathlib_nav_service,
    create_local_toolkit_server,
    create_toolkit_http_client,
    create_lsp_core_client,
    create_lsp_core_service,
    create_lsp_assist_client,
    create_lsp_assist_service,
    create_search_core_client,
    create_search_core_service,
    create_mathlib_nav_client,
    create_mathlib_nav_service,
    create_default_search_nav_client,
    create_default_search_nav_service,
    create_search_nav_client,
    create_search_nav_service,
)
from .toolkit_client import ToolkitHttpClient
from .toolkit_server import ToolkitServer

__all__ = [
    "ToolkitServer",
    "ToolkitHttpClient",
    "create_declarations_service",
    "create_declarations_client",
    "create_default_declarations_service",
    "create_default_declarations_client",
    "create_diagnostics_service",
    "create_diagnostics_client",
    "create_default_diagnostics_service",
    "create_default_diagnostics_client",
    "create_default_lsp_core_service",
    "create_default_lsp_core_client",
    "create_default_lsp_assist_service",
    "create_default_lsp_assist_client",
    "create_default_search_core_service",
    "create_default_search_core_client",
    "create_default_mathlib_nav_service",
    "create_default_mathlib_nav_client",
    "create_local_toolkit_server",
    "create_toolkit_http_client",
    "create_lsp_core_service",
    "create_lsp_core_client",
    "create_lsp_assist_service",
    "create_lsp_assist_client",
    "create_search_core_service",
    "create_search_core_client",
    "create_mathlib_nav_service",
    "create_mathlib_nav_client",
    "create_default_search_nav_service",
    "create_default_search_nav_client",
    "create_search_nav_service",
    "create_search_nav_client",
]
